# Generated by Django 3.2.5 on 2021-07-17 15:25

import django.core.files.storage
from django.db import migrations, models
import utils.uploadprojectimg


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_desc', models.TextField()),
                ('link', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/sevilledev/Desktop/Django/portfolio/media/'), upload_to=utils.uploadprojectimg.upload_project_img)),
                ('details', models.TextField()),
            ],
        ),
    ]
